### ISSUE TITLE
Null Reference Exception when IncludeXmlComments

### ISSUE THREAD

**Issue by lunauM** [domaindrivendev/Ahoy#127]
I included a generated xml of the comments.
I get the following exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.SwaggerGen.Annotations.XmlCommentsIdHelper.GetCommentIdForProperty(PropertyInfo propertyInfo)
   at Swashbuckle.SwaggerGen.Annotations.XmlCommentsModelFilter.ApplyPropertyComments(Schema PropertySchema, PropertyInfo propertyInfo)
   at Swashbuckle.SwaggerGen.Annotations.XmlCommentsModelFilter.Apply(Schema model, ModelFilterContext context)
   at Swashbuckle.SwaggerGen.Generator.SchemaRegistry.CreateObjectSchema(JsonObjectContract jsonContract)
   at Swashbuckle.SwaggerGen.Generator.SchemaRegistry.CreateDefinitionSchema(Type type)
   at Swashbuckle.SwaggerGen.Generator.SchemaRegistry.GetOrRegister(Type type)
   at Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.CreateSuccessResponse(Type responseType, ISchemaRegistry schemaRegistry)
   at Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)

I don't know what could be the problem.

**Comment by lunauM** [comment]
Sorry i just saw that there is already a pull request (#107)which seems to solve the problem
