### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by jwuliger** [domaindrivendev/Ahoy#33]
Hello,

I was hoping to find out when you guys plan on releasing the Beta 8?

I have a Beta 8 MVC 6 App, and I would love to get  Swashbuckle installed. I tried many wasy to try and make the Beta 7 that is on Nuget now work but I keep getting this exception right when services.AddSwagger(); is called.

The Error:
```
System.MissingMethodException was unhandled by user code
  HResult=-2146233069
  Message=Method not found: 'Microsoft.Framework.DependencyInjection.IServiceCollection Microsoft.Framework.DependencyInjection.OptionsServiceCollectionExtensions.Configure(Microsoft.Framework.DependencyInjection.IServiceCollection, System.Action`1<!!0>, Int32, System.String)'.
  Source=Swashbuckle
  StackTrace:
       at Microsoft.Framework.DependencyInjection.SwaggerServiceCollectionExtensions.AddSwagger(IServiceCollection services)
       at RequestIt.Api.Startup.ConfigureServices(IServiceCollection services) in C:\Users\jwuli\Dropbox\Request It Inc\Application\_Prototype\version-1\API\Working Files\RequestIt.Api\Startup.cs:line 42
  InnerException:
```

Thanks for any help or news!

**Comment by domaindrivendev** [comment]
This was released on Nov 2nd 2015.

rc1-final coming soon ...
