### ISSUE TITLE
/swagger/v2/swagger.json results 500 error

### ISSUE THREAD

**Issue by ko-vasilev** [domaindrivendev/Ahoy#69]
I just made the simplest setup for my project, but for some reason it always returns 500 error when I'm trying to get swagger.json file.
This is what I always see when trying to access /swagger/ui/index.html page
http://screencast.com/t/uWxgYZEx

**Comment by domaindrivendev** [comment]
If you navigate directly to the swagger.json endpoint, which is the request that's returning a 500, you should get more detailed error info

**Comment by ko-vasilev** [comment]
Unfortunately I'm getting no extra info, only blank screen.

**Comment by rynowak** [comment]
Are you using the Developer Exception page? https://github.com/aspnet/Mvc/blob/dev/samples/MvcSandbox/Startup.cs#L25

**Comment by ko-vasilev** [comment]
I had no idea about this package and method.
Here is the stack trace that is displayed when trying to access the swagger.json

> System.NotSupportedException: Unbounded HTTP verbs for path 'Api'. Are you missing an HttpMethodAttribute?
   at Swashbuckle.SwaggerGen.DefaultSwaggerProvider.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at Swashbuckle.SwaggerGen.DefaultSwaggerProvider.<>c__DisplayClass4_0.<GetSwagger>b__4(IGrouping`2 group)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.SwaggerGen.DefaultSwaggerProvider.GetSwagger(String apiVersion, String host, String basePath, String[] schemes)
   at Swashbuckle.Application.SwaggerGenMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Swashbuckle.Application.SwaggerUiMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Swashbuckle.Application.RedirectMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ApplicationInsights.AspNet.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ApplicationInsights.AspNet.RequestTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by SimonTouchtech** [comment]
I'm not sure of the exact reason this error occurs, but we were able to fix it by adding an HttpMethodAttribute, just like the error message says. I don't know the implementation details of Swashbuckle and if this requirement could be removed but simply add an [HttpGet] or [HttpPost] or whatever HTTP method you're using above your method and it should do the trick.

**Comment by freshdev1** [comment]
I don't know if this will help someone. But this is how I resolved the exact same issue:
https://github.com/domaindrivendev/Swashbuckle/issues/581#issuecomment-235053027

**Comment by domaindrivendev** [comment]
@SimonTouchtech - regardless of SB, if you don't decorate actions with an explicit [HttpXXX] attribute you're allowing it to be called with any of the HTTP verbs. Rather than second guessing which of the verbs you intend the operation to be called with, SB forces you to be explicit.

The same dilemma arises out of ambiguous model binding when you don't specify what part of the request (uri, header, body etc.) a parameter is populated from - any of them will work and so SB can't guess which you intended.

Despite some criticism around SB forcing you to be explicit (see https://github.com/domaindrivendev/Ahoy/issues/47), I'm strongly against ambiguity in API contracts, to the extent I'm not willing to go out of my way to support it. At least that's my stance as of now :)

**Comment by leeroya** [comment]
This highlighted where to look for the issue, thank you
